"""Add due_date to Ticket

Revision ID: 73801855db77
Revises: 0a5ba662747a
Create Date: 2025-07-30 11:28:14.750639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73801855db77'
down_revision = '0a5ba662747a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
